const EMAIL = "EMAIL";
const TOKEN = "TOKEN";
const PLAN_ID = "PLAN_ID";
const AUTHDATA = "AUTHDATA";
const PLAN_NAME = "PLAN_NAME";
const PROFILE_UPDATE = "PROFILE_UPDATE";
const USERID = "USERID";
const ONBOARDING = "ONBOARDING";
